### ISSUE TITLE
Add appveyor build

### ISSUE THREAD

**Issue by thijstriemstra** [Rantanen/node-opus#63]
This would also demonstrate how to install/build this on windows, besides verifying it actually builds on that platform. And hopefully produce proper windows installation instructions because the majority of tickets in this project are related to windows installation fails.

**Comment by thijstriemstra** [comment]
I can make a pull request for this but some pointers would be useful, I read `system32` needs to be on the path for example?

Here's an example of appveyor failing to install node-opus: https://ci.appveyor.com/project/thijstriemstra/videojs-record/build/1.0.451

```
..\..\deps\opus\silk\float\levinsondurbin_FLP.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\projects\videojs-record\node_modules\node-opus\build\deps\libopus.vcxproj]
  scale_copy_vector_FLP.c
..\..\deps\opus\silk\float\pitch_analysis_core_FLP.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\projects\videojs-record\node_modules\node-opus\build\deps\libopus.vcxproj]
  scale_vector_FLP.c
..\..\deps\opus\silk\float\scale_copy_vector_FLP.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\projects\videojs-record\node_modules\node-opus\build\deps\libopus.vcxproj]
  schur_FLP.c
..\..\deps\opus\silk\float\scale_vector_FLP.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\projects\videojs-record\node_modules\node-opus\build\deps\libopus.vcxproj]
  sort_FLP.c
..\..\deps\opus\silk\float\schur_FLP.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\projects\videojs-record\node_modules\node-opus\build\deps\libopus.vcxproj]
..\..\deps\opus\silk\float\sort_FLP.c(29): fatal error C1083: Cannot open include file: 'config.h': No such file or directory [C:\projects\videojs-record\node_modules\node-opus\build\deps\libopus.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\appveyor\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\videojs-record\node_modules\node-opus
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-opus@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-opus@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2018-09-16T01_22_51_677Z-debug.log
```

**Comment by thijstriemstra** [comment]
Is only opus 1.1 supported? e.g. http://opus-codec.org/release/stable/2017/05/24/libopus-1_1_5.html Any plans for 1.3?

**Comment by Rantanen** [comment]
My tests are broken. :|

I'm not sure what has caused the test failure - I'm suspecting a Node.js version upgrade. The real issue is that what seems to be failing my tests is node-ogg instead of node-opus. For some reason I'm never receiving more than one packet from the ogg streams.

How does this apply to this issue? I tried moving to Opus 1.3 experimentally (I won't be publishing anything until Opus 1.3 is released). I got Opus to compile just fine, but it's hard to figure out whether that's backwards compatible without being able to run the tests on it..

The experimental branch is at https://github.com/Rantanen/node-opus/tree/opus-1.3

There is some real test failure in the encoding tests that results in assertions. I didn't look at what was causing that though. The decoder tests are kind of bumming me out. :|

----------------------

And I'm pretty sure your appveyor compilation issue is due to running the build on 32-bit OS. 32-bit builds are not supported on Windows as no one has contributed a PR for the config.h file. You could try just copying the 64-bit config file and testing a build with it. If you can get the build to work, I'll accept a PR for it. I just don't want to commit anything blindly without being able to test it.

**Comment by thijstriemstra** [comment]
> And I'm pretty sure your appveyor compilation issue is due to running the build on 32-bit OS.

I think appveyor uses 64-bit but you might be right.

**Comment by Rantanen** [comment]
Node is installed in Program Files (x86) according to the paths in the logs so yes, the OS is 64-bit. However the build might still be 32-bit for some reason. That's more or less the only known reason for config.h not being found. If that's not the case, then I don't know what causes it.

**Comment by thijstriemstra** [comment]
I managed to fix the build by specifying 64-bit node on appveyor. PR on it's way.
