### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by superVoja** [Rantanen/node-opus#99]
I am trying to install but I get the same error always 

242 verbose node v12.16.1
243 verbose npm  v6.14.2
244 error code ELIFECYCLE
245 error errno 1
246 error node-opus@0.3.3 install: `node-gyp rebuild`
246 error Exit status 1
247 error Failed at the node-opus@0.3.3 install script.

I have node v12 
Win 10 x64

**Comment by spectral369** [comment]
+1 It's because it contains package ogg-packet which contains ref-struct package which is NOT compatible with node 12+. 
IMO this issue should be top priority for this repo.
My  node -v v12.16.2.
OS: Ubuntu 20.xx LTS
There is a fix in a comment https://github.com/Rantanen/node-opus/issues/93#issuecomment-570787267 which I'll try tomorrow

**Comment by Rantanen** [comment]
I'm archiving the repository for lack of interest in maintaining it. Sorry I never got to deal with this issue. Please see [@discordjs/opus](https://github.com/discordjs/opus) for an alternative implementation that is based this project but uses more stable Node.js module technology that should break less between Node.js versions.
